### ISSUE TITLE
Naamgeving pushes

### ISSUE THREAD

**Issue by Maaike0904** [lemuelmgsn/fix-the-flow-interactive-website#4]
Probeer een goede naam te geven aan je pushes , je hebt nu. [beetje dingen gedaan.](https://github.com/lemuelmgsn/look-and-feel-corporate-identity/commit/9f2065123e762564295572b42b73ba0aa551dcb1) Beschrijf dan wat je hebt gedaan, dan kun je als er later iets fout gaat goed zien wat je goede versie was.

**Comment by lemuelmgsn** [comment]
Yes, zal ik doen!
