### ISSUE TITLE
Link javascript

### ISSUE THREAD

**Issue by Daniquedejong** [lemuelmgsn/fix-the-flow-interactive-website#5]
<script src="script.js"></script>

**Comment by krijnhoetmer** [comment]
Waarschijnlijk heb je hier nog het `defer` attribuut op nodig om het te laten werken: https://developer.mozilla.org/en-US/docs/Web/HTML/Element/script#defer

**Comment by lemuelmgsn** [comment]
Top, thanks, opgelost! :)
