### ISSUE TITLE
Comments

### ISSUE THREAD

**Issue by Maaike0904** [lemuelmgsn/fix-the-flow-interactive-website#9]
Heel goed dat je comments gebruikt. Blijf deze zo schrijven dat je alle code snapt. Vooral met Javascript erg belangrijk dat je weet wat iedere functie doet. Goed bezig 👍🏼

**Comment by krijnhoetmer** [comment]
Eens! Voor een voorbeeldje van hoe je comments kunt inzetten, zie de JavaScript uitleg op https://codepen.io/krijnhoetmer/pen/rNPZGdg

**Comment by lemuelmgsn** [comment]
Bedankt!
